config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "category/:id",  to: "category_lists#index", as: "category"
  get 'items_log/index'
  get 'carts/index'
  post "carts/:id", to: "carts#create", as: "carts_add"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout",to: "sessions#destroy"
  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :items
  resources :carts, only: [:destroy, :index]
  resources :profiles, only: [:edit, :update]
  resources :orders, only: [:new, :create, :destroy, :update]
  resources :order_cancels, only: [:update]
  resources :contacts, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_accessor :remember_token, :activation_token, :reset_token
  after_create :profile_create
  before_save :downcase_email
  before_create :create_activation_digest
  has_one :profile, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
  mount_uploader :user_phote, UserPhoteUploader
  mount_uploader :background_phote, BackgroundPhoteUploader
  validates :user_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
    end

    def forget
      update_attribute(:remember_digest, nil)
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def create_reset_digest
      self.reset_token = User.new_token
      update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
    end

    def downcase_email
      self.email = email.downcase
    end
 # パスワード再設定のメールを送信する
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

    def already_cart_exist?(item)
      self.carts.exists?(item_id: item.id)
    end

    def profile_create
      self.build_profile.save(validate: false)
    end

  # private

    # アップロードされた画像のサイズをバリデーションする
    # def picture_size
    #   if picture_size > 5.megabytes
    #     errors.add(:picture, "should be less than 5MB")
    #   end
    # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :admin_user,  only: :destroy
  before_action :logged_in_user, only: [:edit, :destroy, :show, :update]
  before_action :correct_user, only: [ :edit, :destroy, :show, :update]

  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "アカウント有効化のためのメールを送信しました。ご確認ください。"
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "編集しました"
      redirect_to @user
    else
      render "edit"
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @order = Order.new
    @before_item_history = current_user.orders.where(status: false)
    @after_item_history = current_user.orders.where(status: true)
    @cancel_item = current_user.orders.where(cancel_status: true)
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = "アカウントを削除しました。"
    redirect_to root_url
  end

  private

    def user_params
      params.require(:user).permit(:user_name, :email, :password,
                                      :password_confirmation, :background_phote, :user_phote, :user_content)
    end


   def correct_user
     @user = User.find_by(id: params[:id])
     redirect_to(root_url) unless @user == current_user
   end

    # def admin_user
    #   # redirect_to(root_url) unless current_user.admin?
    #
    # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "編集") %>
  <article class="edit-container">
    <section>
      <%= form_for(@user) do |f| %>
      <div id="background-phote-field" onClick="$('#background-phote-file').click()" >
        <% if @user.background_phote.file.nil?%>
        <%= image_tag "default_background_phote.jpg"%>
        <!-- <span class="fas fa-camera"></span> -->
        <% else %>
        <%= image_tag @user.background_phote.to_s%>
        <%end%>
      </div>
      <div id="user-phote-field" onClick="$('#user-phote-file').click()" >
        <% if @user.user_phote.file.nil?%>
          <%= image_tag "default_user_phote.png"%>
        <!-- <span class="fas fa-camera"></span> -->
        <% else %>
          <%= image_tag @user.user_phote.to_s%>
        <%end%>
      </div>
      <%= f.file_field :background_phote , style: "display:none;", id: "background-phote-file",accept: 'image/jpeg,image/gif,image/png'%>
      <%= f.file_field :user_phote ,style: "display:none;", id: "user-phote-file", accept: 'image/jpeg,image/gif,image/png'%>
      <div class="edit-form">
        <%= render 'shared/error_messages', object: f.object  %>
        <span class="edit-input">
          <%= f.label :user_name, "ニックネーム" %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </span>
        <span class="edit-textarea">
          <%= f.label :user_name, "自己紹介" %>
          <%= f.text_area :user_content, class: 'form-textarea' %>
        </span>
        <span class="edit-input">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: 'form-control' %>
        </span>
        <span class="edit-input">
          <%= f.label :password, "新しいパスワード" %>
          <%= f.password_field :password, class: 'form-control' %>
        </span>
        <span class="edit-input">
          <%= f.label :password_confirmation, "パスワード確認" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </span>
        <%= f.submit "変更", id: "edit-btn" %>
      </div>

      <div class="edit-link-list">
        <ul>
          <li><a href="#"><span class="fas fa-angle-left"></span>お届け先　住所変更</a></li>
          <li><a href="#"><span class="fas fa-angle-left"></span>支払方法確認</a></li>
          <li>
            <%= link_to user_path(@user), method: :delete , class: "user" do%>
            <span class="fas fa-angle-left"></span>
            アカウント削除
            <%end%>
          </li>
        </ul>
      </div>

      <% end %>
    </section>

  </article>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<article class="signup-container">
  <div class="inner signup-inner">
    <h1>新規登録</h1>
    <section class="signup-form">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :user_name, "ニックネーム", class: "signup-nickname"%>
        <%= f.text_field :user_name %>

        <%= f.label :email, "メールアドレス", class: "signup-email" %>
        <%= f.email_field :email %>

        <%= f.label :password, "パスワード", class: "signup-password" %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "パスワード確認", class: "signup-password-confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "作成", id: "new_user_btn" %>

      <% end %>
    </section>
  </div>
</article>

app/views/users/show.html.erb
<%provide(:title, "ユーザー詳細")%>

<article class="show-container items-log-container">
  <%= render "shared/user_show" %>
  <div class="inner">
    <section class="items-log-list">
      <h1>注文ログ</h1>
      <h2>発送前</h2>
      <ul id="items-log-list">
        <% if @before_item_history.empty? %>
          <p id="orders-empty-commant">現在注文はありません</p>
        <% else %>
          <p id="order-info">商品が届いたらお届け完了ボタンを押してください</p>
          <% @before_item_history.each do |orders|%>
            <li>
              <%= image_tag orders.item.item_phote[0].to_s %>
              <div>
                <p><%= orders.item.title %></p>
                <p>月額￥<%= orders.item.price %></p>
                <%= link_to "お届け完了",order_path(orders.id), method: :put, class: "delivery-finish-btn" %>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
      <h2>発送後(現在取引中)</h2>
      <ul id="items-log-list">
        <% if @after_item_history.empty? %>
          <p>注文はありません</p>
        <% else %>
          <% @after_item_history.each do |orders| %>
            <% if orders.cancel_status == false %>
              <li>
                <%= image_tag orders.item.item_phote[0].to_s %>
                <div>
                  <p><%= orders.item.title %></p>
                  <p>月額￥<%= orders.item.price %></p>
                  <%= link_to "shere終了",order_cancel_path(orders.id), method: :put, class: "delivery-finish-btn" %>
                </div>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
      <h2>発送後(取引終了)</h2>
      <ul id="items-log-list">
        <% if @cancel_item.empty? %>
          <p>取引を終了した商品はありません</p>
        <% else %>
          <% @cancel_item.each do |orders| %>
            <li>
              <%= image_tag orders.item.item_phote[0].to_s %>
              <div>
                <p><%= orders.item.title %></p>
                <p>月額￥<%= orders.item.price %></p>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </section>
  </div>
  <span class="post-item"><%= link_to "出品",new_item_path %></span>
</article>