config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "category/:id",  to: "category_lists#index", as: "category"
  get 'items_log/index'
  get 'carts/index'
  post "carts/:id", to: "carts#create", as: "carts_add"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout",to: "sessions#destroy"
  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :items
  resources :carts, only: [:destroy, :index]
  resources :profiles, only: [:edit, :update]
  resources :orders, only: [:new, :create, :destroy, :update]
  resources :order_cancels, only: [:update]
  resources :contacts, only: [:new, :create]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      フォーム入力に <%= pluralize(object.errors.count, "つのエラーがあります") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_show.html.erb
<section　class="user_acount">
  <p class="background-phote">
    <% if @user.background_phote.file.nil?%>
      <%= image_tag "default_background_phote.jpg"%>
    <!-- <span class="fas fa-camera"></span> -->
    <% else %>
      <%= image_tag @user.background_phote.to_s%>
    <%end%>
  </p>
  <p class="user_phote">
    <% if @user.user_phote.file.nil?%>
      <%= image_tag "default_user_phote.png"%>
    <!-- <span class="fas fa-camera"></span> -->
    <% else %>
      <%= image_tag @user.user_phote.to_s%>
    <%end%>
  </p>
  <p id="user_name"><%= @user.user_name %></p>
  <p id="user_content"><span><%= @user.user_content %></span></p>
  <ul>
    <span class="inner show-link-inner">
      <li><%= link_to "編集",edit_user_path(@user.id) %></li>
      <li><%= link_to "出品ログ", items_log_index_path %></li>
      <li><%= link_to "カート", carts_path %></li>
      <li><a href="#">売上</a></li>
      <li><%=link_to "ログアウト", logout_path, method: :delete %></li>
    </span>
  </ul>
</section>