config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "category/:id",  to: "category_lists#index", as: "category"
  get 'items_log/index'
  get 'carts/index'
  post "carts/:id", to: "carts#create", as: "carts_add"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout",to: "sessions#destroy"
  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :items
  resources :carts, only: [:destroy, :index]
  resources :profiles, only: [:edit, :update]
  resources :orders, only: [:new, :create, :destroy, :update]
  resources :order_cancels, only: [:update]
  resources :contacts, only: [:new, :create]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
  self.inheritance_column = :_type_disabled
  mount_uploaders :item_phote, ItemPhoteUploader
  validates :user_id, presence: true
  validates :item_content, length: { maximum: 250 }
  enum category: { furniture: 0, music: 1, accessories: 2, clothes: 3, book: 4, game: 5 }
  enum item_status: { new_item: 0, nodirt_item: 1, dirt_item: 2, bad_item: 3 }
  enum shipping_charge: { exhibitor_burden: 0, buyer_burden: 1 }

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"]).where(sales: false)
    else
     all #全て表示。User.は省略
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  before_action :profile_check, only: [:new]
  # before_action :already_soled_item, only: [:show]

  def new
    @item = current_user.items.build
  end

  def create
    # binding.pry
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "出品しました"
      redirect_to @item
    else
      render "items/new"
    end
  end

  def show
    @item = Item.find_by(id: params[:id])
    @user = @item.user
    @items = @user.items
    @cart_item = Cart.new
    @order = Order.new
  end

  def destroy
    @item = Item.find_by(id: params[:id])
    @item.destroy
    flash[:success] = "出品を取り消しました"
    redirect_to root_url
  end

  def index
    @items = Item.page(params[:page]).per(30).search(params[:search]).order(created_at: :desc)
    @item_heading= params[:search]
    unless @item_heading
      @item_heading = "すべて"
    end
  end

  private

    def item_params
      params.require(:item).permit(:title, :item_content, :price, :category,
                                      :item_status, :shipping_charge, :type, :days,{item_phote: [] } )
    end

    def correct_user
      @item = current_user.items.find_by(id: params[:id])
      redirect_to root_url if @item.nil?
    end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%provide(:title, "出品物一覧")%>
<article class="item-index-container">
  <div class="inner item-index-inner">
    <h1><%= @item_heading %></h1>
    <!-- <ul class="item-index-sort">
      <li><a href="#">人気順</a></li>
      <li><a href="#">価格低い順</a></li>
      <li><a href="#">価格高い順</a></li>
    </ul> -->
    <% if @items.empty? %>
      <p>検索結果に当てはまる商品はありませんでした。</p>
    <% else %>
      <ul class="item-index-list">
        <% @items.each do|item| %>
          <% unless Order.find_by(item_id: item.id) %>
            <%= link_to item_path(item), class: "item" do%>
              <li>
                <%= image_tag item.item_phote[0].to_s%>
                <p><%= item.title %></p>
                <p>月額￥<%= item.price %></p>
              </li>
            <% end %>
          <% end%>
        <% end %>
      </ul>
      <%= paginate @items%>
    <% end %>
  </div>
</article>

app/views/items/new.html.erb
<% provide(:title, "出品登録") %>
<article class="post-item-container">
  <h1>出品商品情報</h1>
  <div class="post-item-form">
    <%= form_for(@item) do |f| %>

    <%= f.label :item_phote,"画像(5枚まで)" %>
    <span id="item-phote-field" onClick="$('#item-phote-file').click()"></span>
    <%= f.file_field :item_phote ,multiple: true , id: "item-phote-file", style: "display:none;", accept: 'image/jpeg,image/gif,image/png'%>

    <%= f.label :item_phote,"画像(5枚まで)" %>
    <span id="item-phote-field2" onClick="$('#item-phote-file2').click()"></span>
    <%= f.file_field :item_phote ,multiple: true , id: "item-phote-file2", style: "display:none;", accept: 'image/jpeg,image/gif,image/png'%>

    <%= f.label :item_phote,"画像(5枚まで)" %>
    <span id="item-phote-field3" onClick="$('#item-phote-file3').click()"></span>
    <%= f.file_field :item_phote ,multiple: true , id: "item-phote-file3", style: "display:none;", accept: 'image/jpeg,image/gif,image/png'%>

    <%= f.label :item_phote,"画像(5枚まで)" %>
    <span id="item-phote-field4" onClick="$('#item-phote-file4').click()"></span>
    <%= f.file_field :item_phote ,multiple: true , id: "item-phote-file4", style: "display:none;", accept: 'image/jpeg,image/gif,image/png'%>

    <%= f.label :item_phote,"画像(5枚まで)" %>
    <span id="item-phote-field5" onClick="$('#item-phote-file5').click()"></span>
    <%= f.file_field :item_phote ,multiple: true , id: "item-phote-file5", style: "display:none;", accept: 'image/jpeg,image/gif,image/png'%>

    <%= f.label :title, "商品名" %>
    <%= f.text_field :title %>

    <%= f.label :item_content, "商品説明" %>
    <%= f.text_area :item_content %>

    <p>商品について</p>

    <ul class="post-item-selector">
      <li>
        <%= f.label :category, "カテゴリー", class: "signup-password" %>
        <%= f.select :category, Item.categories_i18n.invert, {}, placeholder: 0  %>
      </li>
      <li>
        <%= f.label :shipping_charge, "配送料負担", class: "signup-password" %>
        <%= f.select :shipping_charge, Item.shipping_charges_i18n.invert, {}, placeholder: 0 %>
      </li>
      <li>
        <%= f.label :item_status, "商品状態", class: "signup-password" %>
        <%= f.select :item_status, Item.item_statuses_i18n.invert, {}, placeholder: 0 %>
      </li>
    </ul>

    <%= f.label :days, "配送にかかる日数"%>
    <%= f.text_field :days %>

    <%= f.label :price, "価格"%>
    <%= f.text_field :price %>

    <%= f.submit "出品", id: "post_item_btn" %>

    <% end %>
  </div>
</article>

app/views/items/show.html.erb
<article class="item-show-container">
  <h1 class="show-item-title"><%= @item.title%></h1>
  <div class="inner">
    <section class="item-introduction">
      <div class="left-side">
        <ul class="show-item-phote">
          <li><%= image_tag @item.item_phote[0].to_s%></li>
          <% if @item.item_phote[1] %>
          <ul>
            <li><%= image_tag @item.item_phote[1].to_s%></li>
            <% if @item.item_phote[2] %>
            <li><%= image_tag @item.item_phote[2].to_s%></li>
            <% end %>
          </ul>
          <%end%>
          <% if @item.item_phote[3] %>
          <ul>
            <li><%= image_tag @item.item_phote[3].to_s%></li>
            <% if @item.item_phote[4] %>
            <li><%= image_tag @item.item_phote[4].to_s%></li>
            <% end %>
          </ul>
          <%end%>
        </ul>
        <ul class="left-side-link">
          <% if current_user == @item.user %>
          <li class="item-show-destroy"> <%= link_to "出品取り消し" , @item ,  method: :delete %></li>
          <% end %>
        </ul>
      </div>
      <div class="right-side">
        <p class="item-show-price">月額￥<%= @item.price %></p>
        <ul class="show-item-link">
            <li>
              <% if current_user.already_cart_exist?(@item)%>
                <%= button_to "カートに追加済み", cart_path(@item), method: :delete, class: "show-already-cart-link show-cart" %>
              <% else %>
                <%= button_to "カートに追加", carts_add_path(@item), class: "show-cart-link show-cart" %>
              <% end %>
            </li>
          <li>
            <%= link_to "今すぐシェア", new_order_path(@item), class: "shere-btn" %>
          </li>
        </ul>
        <h1 class="show-item-details-midasi">この商品について</h1>
        <ul class="show-item-details">
          <li>
            <p>出品者名</p>
            <p><%= @item.user.user_name %></p>
          </li>
          <li>
            <p>商品状態</p>
            <p><%= @item.item_status_i18n %></p>
          </li>
          <li>
            <p>配送料の負担</p>
            <p><%= @item.shipping_charge_i18n %></p>
          </li>
          <li>
            <p>配送日の目安</p>
            <p><%= @item.days %>日</p>
          </li>
          <li>
            <p>説明</p>
            <p><%= @item.item_content %></p>
          </li>
        </ul>
      </div>
    </section>
  </div>
  <div class="inner">
    <section class="show-item-slide">
      <h1><%= @user.user_name%>様の出品物</h1>
      <div class="swiper-container" id="show-swipper-container">
      <!-- Sliderの内包コンテナ -->
        <div class="swiper-wrapper">
          <% @items.each do |item| %>
            <div class="swiper-slide" id="show-swiper-slide">
              <%= link_to item_path(item), class: "item" do%>
                <%= image_tag item.item_phote[0].to_s%>
                <p><%= item.title%></p>
                <p>月額￥<%= item.price%></p>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
      </div>
    </section>
  </div>

</article>
<script type="text/javascript">
  var mySwiper = new Swiper ('.swiper-container', {
// ここからオプション
    loop: true,
    slidesPerView: 4,
    spaceBetween: 20 ,
    initialSlide: 2,
    pagination: {
      el: '.swiper-pagination',
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    scrollbar: {
      el: '.swiper-scrollbar',
    }
  })
</script>