config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get "category/:id",  to: "category_lists#index", as: "category"
  get 'items_log/index'
  get 'carts/index'
  post "carts/:id", to: "carts#create", as: "carts_add"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout",to: "sessions#destroy"
  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :items
  resources :carts, only: [:destroy, :index]
  resources :profiles, only: [:edit, :update]
  resources :orders, only: [:new, :create, :destroy, :update]
  resources :order_cancels, only: [:update]
  resources :contacts, only: [:new, :create]
end

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li>
      <a href="/">nicoichi</a>
    </li>
    <li>
      <a href="/help">ヘルプ＆ガイド</a>
    </li>
    <li>
      <a href="#">注意事項</a>
    </li>
    <li>
    <%= link_to "お問い合わせ",  new_contact_path %>
    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="inner header-inner">
    <h1><%= link_to "nicoichi", root_path%></h1>
    <%= form_tag(items_path, method: "get", class: "serch-form")do %>
      <%= text_field_tag :search, "", placeholder: '何かお探しですか' %>
      <%= button_tag :type => "submit", :title => nil do %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    <% end %>
    <% if logged_in? %>
      <p class="header-show-link">
        <%= link_to current_user, class: "user" do%>
          <% image_tag current_user.user_phote.to_s  %>
        <%end%>
      </p>
      <%= link_to carts_path do %>
        <span class="fas fa-cart-plus cart"></span>
      <% end %>
    <% else %>
      <p class="header-signup-link"><%= link_to "新規登録", new_user_path %></p>
      <p class="header-login-link"><%= link_to "ログイン", login_path %></p>
    <% end %>
  </div>
  <div class="category-link">
    <ul>
        <li>
          <a class="category-serch">カテゴリーから探す</a>
          <ul class="category-list hidden">
            <li><%= link_to "インテリア/小物", category_path(5) %></li>
            <li><%= link_to "家電", category_path(6) %></li>
            <li><%= link_to "ゲーム/おもちゃ", category_path(7) %></li>
            <li><%= link_to "コスメ/美容", category_path(8) %></li>
            <li><%= link_to "スポーツ", category_path(9) %></li>
            <li><%= link_to "ハンドメイド", category_path(10) %></li>
          </ul>
        </li>
        <li>
          <%=link_to "すべて", items_path %>
        </li>
        <li>
          <%= link_to "家具", category_path(0) %>
        </li>
        <li>
          <%= link_to "ファッション", category_path(3) %>
        </li>
        <li>
          <%= link_to "アクセサリー", category_path(2) %>
        </li>
        <li>
          <%= link_to "本", category_path(4) %>
        </li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>
    <script type="text/javascript" src="jquery.jpostal.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render'layouts/footer' %>
    <script>

  $(function(){
  	$('.question').click(function(){
  		$(this).next('.answer').slideToggle();
      $(this).toggleClass("ac");
  	});

    $(function(){
      $('.category-serch').hover(function(){
          $(this).next().toggleClass("hidden");
      })
    })

    // $(function(){
    //   $("#profile_postcode").jpostal({
    //     postcode : [ "#profile_postcode" ],
    //     address  : {
    //                   "#profile_prefecture_code" : "%3",
    //                   "#profile_address_city"            : "%4",
    //                   "#profile_address_street"          : "%5%6%7"
    //                 }
    //   })
    // })

    $(function(){
      $fileField = $('#background-phote-file')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#background-phote-field");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });

    $(function(){
      $fileField = $('#user-phote-file')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#user-phote-field");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });

    $(function(){
      $fileField = $('#item-phote-file')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#item-phote-field");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });

    $(function(){
      $fileField = $('#item-phote-file2')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#item-phote-field2");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });
    $(function(){
      $fileField = $('#item-phote-file3')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#item-phote-field3");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });
    $(function(){
      $fileField = $('#item-phote-file4')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#item-phote-field4");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });
    $(function(){
      $fileField = $('#item-phote-file5')

      // 選択された画像を取得し表示
      $($fileField).on('change', $fileField, function(e) {
        file = e.target.files[0]
        reader = new FileReader(),
        $preview = $("#item-phote-field5");

        reader.onload = (function(file) {
          return function(e) {
            $preview.empty();
            $preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              class: "preview",
              title: file.name
            }));
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });


  });
    </script>
  </body>
</html>